apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: flask
spec:
  vars:
  - name: image
    value: 302879626612.dkr.ecr.eu-central-1.amazonaws.com/flask
  - name: repoURL
    value: https://github.com/sainyusuf/eks-gitops.git
  - name: branch
    value: main
  - name: envPath
  - name: argocdApp

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./out
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/${{ vars.envPath }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image ).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    as: push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.argocdApp }}
