apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: flask
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: flask
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: 03_argocd/env/dev/flask
        - name: argocdApp
          value: flask-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: flask
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: flask
    sources:
      stages:
        - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: 03_argocd/env/staging/flask
        - name: argocdApp
          value: flask-staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: flask
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: flask
    sources:
      stages:
        - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: envPath
          value: 03_argocd/env/prod/flask
        - name: argocdApp
          value: flask-prod
