apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: flask
  namespace: flask
spec:
  subscriptions:
  - image:
      repoURL: 302879626612.dkr.ecr.eu-central-1.amazonaws.com/flask
      imageSelectionStrategy: Lexical
      discoveryLimit: 10
