server:
  extraArgs:
    - --insecure
  service:
    type: NodePort
  serviceAccount:
    name: argocd-server
    annotations:
      eks.amazonaws.com/role-arn: ${argocd_iam_role_arn}
  # tolerations:
  #   - key:    "node-role.kubernetes.io/system"
  #     operator: "Exists"
  #     effect:   "NoSchedule"

# repoServer:
#   tolerations:
#     - key:    "node-role.kubernetes.io/system"
#       operator: "Exists"
#       effect:   "NoSchedule"

# applicationController:
#   tolerations:
#     - key:    "node-role.kubernetes.io/system"
#       operator: "Exists"
#       effect:   "NoSchedule"

redis:
  persistence:
    storageClass: gp3
  # tolerations:
  #   - key:    "node-role.kubernetes.io/system"
  #     operator: "Exists"
  #     effect:   "NoSchedule"

configs:
  params:
    server.insecure: "true"
  cm:
    url: https://argocd.tukang-awan.com
    data.url: https://argocd.tukang-awan.com
    admin.enabled: true
  secret:
    admin.password: "$2a$10$zBMumLfx/DzU6.13S7N9ZuW6q1GdRNff.Wyo2roSE13u1xnfEoM5i"
