apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flask
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: flask-*
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/sainyusuf/eks-gitops.git
