apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sainyusuf/eks-gitops.git
      revision: main
      directories:
      - path: 03_argocd/env/*
  template:
    metadata:
      name: flask-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: "flask:{{path.basename}}"
    spec:
      destination:
        namespace: flask-{{path.basename}}
        server: https://kubernetes.default.svc
      project: flask
      source:
        path: 03_argocd/charts/flask
        repoURL: https://github.com/sainyusuf/eks-gitops.git
        targetRevision: main
        helm:
          valueFiles:
            - "03_argocd/env/{{path.basename}}/flask/values.yaml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
